CREATE DATABASE `TESTDB` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;

USE TESTDB;
DROP TABLE IF EXISTS `TEST_TABLE`;
CREATE TABLE `TEST_TABLE` (
  `ID` int(10) NOT NULL AUTO_INCREMENT,
  `FIRST_NAME` varchar(255) DEFAULT NULL UNIQUE,
  `LAST_NAME` varchar(255) DEFAULT NULL UNIQUE,
  `SEX` SET('M','F') NOT NULL DEFAULT 'M',
  `AGE` int(3) DEFAULT NULL,
  `INCOME` DECIMAL(12,2) DEFAULT NULL,
  PRIMARY KEY (`ID`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

GRANT ALL PRIVILEGES ON TESTDB.* TO 'testuser'@'localhost' IDENTIFIED BY 'test123';
